---
- name: tcp port for raft
  firewalld:
    port: "{{ etcd_raft_port }}/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: tcp port for etcd connection
  firewalld:
    port: "{{ etcd_connection_port }}/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: kubernetes master port
  firewalld:
    port: "{{ k8s_master_port }}/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: kubernetes firewall rule
  firewalld:
    port: "10250/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: kubernetes firewall rule
  firewalld:
    port: "10251/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: kubernetes firewall rule
  firewalld:
    port: "10252/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: kubernetes firewall rule
  firewalld:
    port: "10255/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: calico networking port
  firewalld:
    port: "179/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
